/*******************************************************************************
**  DAVE App Name : CCU8GLOBAL       App Version: 1.0.14               
**  This file is generated by DAVE, User modification to this file will be    **
**  overwritten at the next code generation.                                  **
*******************************************************************************/


/*CODE_BLOCK_BEGIN[CCU8GLOBAL.c]*/

/*******************************************************************************
 Copyright (c) 2011, Infineon Technologies AG                                 **
 All rights reserved.                                                         **
                                                                              **
 Redistribution and use in source and binary forms, with or without           **
 modification,are permitted provided that the following conditions are met:   **
                                                                              **
 *Redistributions of source code must retain the above copyright notice,      **
 this list of conditions and the following disclaimer.                        **
 *Redistributions in binary form must reproduce the above copyright notice,   **
 this list of conditions and the following disclaimer in the documentation    **
 and/or other materials provided with the distribution.                       **
 *Neither the name of the copyright holders nor the names of its contributors **
 may be used to endorse or promote products derived from this software without**
 specific prior written permission.                                           **
                                                                              **
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"  **
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE    **
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE   **
 ARE  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE   **
 LIABLE  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR         **
 CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF         **
 SUBSTITUTE GOODS OR  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS    **
 INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN      **
 CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)       **
 ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE   **
 POSSIBILITY OF SUCH DAMAGE.                                                  **
                                                                              **
 To improve the quality of the software, users are encouraged to share        **
 modifications, enhancements or bug fixes with Infineon Technologies AG       **
 dave@infineon.com).                                                          **
                                                                              **
********************************************************************************
**                                                                            **
**                                                                            **
** PLATFORM : Infineon XMC4000/XMC1000 Series                          **
**                                                                            **
** COMPILER : Compiler Independent                                            **
**                                                                            **
** AUTHOR   : App Developer                                                   **
**                                                                            **
** MAY BE CHANGED BY USER [yes/no]: Yes                                       **
**                                                                            **
** MODIFICATION DATE : January 22, 2013                                       **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                       Author(s) Identity                                   **
********************************************************************************
**                                                                            **
** Initials     Name                                                          **
** ---------------------------------------------------------------------------**
** PM       App Developer                                                 **
*******************************************************************************/

/**
 * @file  CCU8GLOBAL.c
 *
 * @brief This file contains implementations of all Public and Private functions
 *        of CCU8GLOBAL App.
 */
/*Revision History
 * 22 March   2012   v1.0.0    Initial version
 * 17 Sept    2012   v1.0.4    removed the function like macro to abide coding rules 
 * 							   Disabling of Clock gating added for XMC44 devices
 * 22 Jan     2013   v1.0.8    Disabling of Clock gating added for XMC1xxx devices
 */
/*******************************************************************************
**                      Include Files                                         **
*******************************************************************************/

#include "../../inc/CCU8GLOBAL/CCU8GLOBAL.h"



/*******************************************************************************
**                 Public Function declarations                              **
*******************************************************************************/

/**
 * @cond INTERNAL_DOCS
 */
void CCU8GLOBAL_Init(void)
{
  static uint32_t isInitialized = (uint32_t)0;
  if(!isInitialized){
        
	isInitialized++;
    
    /* Initialise the clock */
	
	CLK002_Init();
	
    
    /* Disables the gating for CCU8 kernel */
    /*This is applicable for XMC4400,XMC4200 and XMC1xxx Devices*/
	if (!((uint32_t)SCU_CLK->CGATCLR0 & (uint32_t)SCU_CLK_CGATCLR0_CCU80_Pos)){ 
	SCU_GENERAL->PASSWD = 0x000000C0UL;
	WR_REG(SCU_CLK->CLKCR, SCU_CLK_CLKCR_CNTADJ_Msk, SCU_CLK_CLKCR_CNTADJ_Pos,CLK002_DELAYCNT);
	SET_BIT(SCU_CLK->CGATCLR0, SCU_CLK_CGATCLR0_CCU80_Pos);
	while ((uint32_t)SCU_CLK->CLKCR & (uint32_t)SCU_CLK_CLKCR_VDDC2LOW_Msk)
	{	
		;
	}
	SCU_GENERAL->PASSWD = 0x000000C3UL;
	}
	 
    
    
    /* Set the prescalar run bit */
    SET_BIT(CCU8Global_Handle0.CC8yKernRegsPtr->GIDLC,CCU8_GIDLC_SPRB_Pos);
    
  }
}
/**
 * @endcond
 */
/*CODE_BLOCK_END*/

