/*******************************************************************************
**  DAVE App Name : NVIC_SR101       App Version: 1.0.2               
**  This file is generated by DAVE, User modification to this file will be    **
**  overwritten at the next code generation.                                  **
*******************************************************************************/

 

/* CODE_BLOCK_BEGIN[NVIC_SR101_Conf.h] */
/******************************************************************************
 *
 * Copyright (C) 2012 Infineon Technologies AG. All rights reserved.
 *
 * Infineon Technologies AG (Infineon) is supplying this software for use with 
 * Infineon's microcontrollers.
 * This file can be freely distributed within development 
 * tools that are supporting such microcontrollers. 
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * INFINEON SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR
 * CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
********************************************************************************
**                                                                            **
**                                                                            **
** PLATFORM : Infineon XMC1000 Series                                         **
**                                                                            **
** COMPILER : Compiler Independent                                            **
**                                                                            **
** AUTHOR : App Developer                                                     **
**                                                                            **
** MAY BE CHANGED BY USER [yes/Yes]: Yes                                      **
**                                                                            **
** MODIFICATION DATE : Feb 04, 2013                                           **
**                                                                            **
*******************************************************************************/
/*******************************************************************************
**                       Author(s) Identity                                   **
********************************************************************************
**                                                                            **
** Initials    Name                                                           **
** ---------------------------------------------------------------------------**
** SK          App Developer                                                  **
*******************************************************************************/
 
/**
  * @App Version NVIC_SR101_CONF_H <1.0.2>
  * 
  * @file   NVIC_SR101_Conf.h
  *
  * @brief  This file has the App instance configurations.
  *
  */
/* Revision History */
/* 31-01-13 v0.1.0 Inital version
 * 04-02-13 v0.1.3 App version added
 */
 #ifndef NVIC_SR101_CONF_H_
 #define NVIC_SR101_CONF_H_
 
/**
 * @}
 */

#endif /* NVIC_SR101_CONF_H*/
/*CODE_BLOCK_END*/

