/*******************************************************************************
**  DAVE App Name : UART001       App Version: 1.0.18               
**  This file is generated by DAVE, User modification to this file will be    **
**  overwritten at the next code generation.                                  **
*******************************************************************************/


/*CODE_BLOCK_BEGIN[UART001_Conf.h]*/
/******************************************************************************
 *
 * Copyright (C) 2011 Infineon Technologies AG. All rights reserved.
 *
 * Infineon Technologies AG (Infineon) is supplying this software for use with 
 * Infineon's microcontrollers.  
 * This file can be freely distributed within development tools that are 
 * supporting such microcontrollers. 
 *
 * THIS SOFTWARE IS PROVIDED "AS IS".  NO WARRANTIES, WHETHER EXPRESS, IMPLIED
 * OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE.
 * INFINEON SHALL NOT, IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, 
 * OR CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.
 *
*******************************************************************************
**                                                                           **
**                                                                           **
** PLATFORM : Infineon XMC4000/ XMC1000 Series                               **
**                                                                           **
** COMPILER : Compiler Independent                                           **
**                                                                           **
** AUTHOR   : App Developer                                                  **
**                                                                           **
** MAY BE CHANGED BY USER [yes/no]: Yes                                      **
**                                                                           **
**                                                                           **
******************************************************************************/
/**
 * @file   UART001_Conf.h
 * 
 * @App Version UART001 <1.0.18>
 *
 * @brief  Configuration file generated based on UI settings 
 *         of UART001 App
 *
 */
#ifndef _CONF_UART001_H_
#define _CONF_UART001_H_

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
** @Defines
*****************************************************************************/

#include <DAVE3.h>


/*Base Address of mapped USIC Module for App Instance 0 */
#define UART001_0_USIC 	  USIC0
/*Base Address of mapped USIC Channel for App Instance 0 */
#define UART001_0_USIC_CH  USIC0_CH1

extern const UART001_HandleType UART001_Handle0; 



#ifdef __cplusplus
}
#endif   

#endif /* End of _CONF_UART001_H_ */
/*CODE_BLOCK_END*/

